language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
env:
  global:
    - secure: "pqfGVhGyhFUwCPEV+WvMAraXI1KcuDX8Y/uPGSh6vqw9dwxdvJ1SBy+5hEnH5gWWTXktq0s92IPonJUC+hCrqRKCxXPEK4sfy1kYmwRc5szpgJ63ZjntF6358Ai3C+uY1ViWl+Re7hSJ4YvD90oHANi1z0zJeOc8Oqiq+nbUzbhMG86QGEQvaO3LjZOmOvf5HSu5F1MnoMLj4oxJM3n9XSqhDTDva6V40clOp0/x3IQVoWYjp/auV/+iJC+UBYX6+kgnX5AJvfKPv/hVHsbsheLJUJNgjL9sGg8xCZc6Du/Xt0uYsvzn42YODSD81jEF+Jfpwcjc3j+XOEzXCWookdXBJzeATMFzkzbsvPfrSdt+9rOKJS1AQ1860t6bJ+o/icvBEVdE0SKva43pwt2CiLgvXL2xiRlU7uN2E7IRvaPul6iTN+Rh/qk1dehz7JlOtq3U2XpbPQn6SBSSnbY49orUxEJ+rBkSLXEYbBMe1yYprZkTCl3Mso+s5y6q1QqviruDEprGhCpxNtqLKDpnwOlY53T6Qp45vQJAGMnHr0jQDane/VFHjmlfWeM7iwWx+0KGS5btLPb4ZskpbIJq7sbBAimhmBAQ1erSUfYkK9vawSrkxehWPukApGMhdM4dSrtWFi6NG6NQ2xj1/QP8q6bIJuiUeb0FS7pFSKCpngw="
    - secure: "d+3IJSnTOIly935agRmkQ3vznuk7MspTD4KXPesVraKEmw+cd7DcqWgQa+OqFG5IvS+5Hqr2T7sZh6M+7QMokbjf7C7vytqKXQXSFEQ4q/ZVlGDpFjOxOloBLa/v5Cy0+0qkDwty/FeW3D5BIkjbvePZEh1AyuG9M2KP8MTkVgc05DonZChdGtIKrps7SpoEwqw+5Y3XsG6JeIsO+rwJ25GGofIGAiYhg8/GoMQ1ep+J3hKAueMDc2gjC9KGEscN1fZFATBNY9kbhkk4DcwZdKce9/C2KlrI6dmmZLpelyB65Kqqqb6/6aGDLl19ldd+es4qBKvq5u1DWjmA33Fj9d0RknJQx/EOwcx03fpsoUwJLYxRHiBS/6hvHgnroqXzkdPh/ZptWvXqXtjXTgpfP4Z9C3FvQAbr9ELxUeH2OY5Y2o7VYh9xESHTVwYSdoLJJPuCmelyJdzFiT0GIWgIBd2rUEbWeVgHCy7ny31X3sIuE70hcdJ+5JYOiQWwcfuWT126yUogbQCKizQa9phDa/1zy0vJh+fzEE5mdo57nNTBCkcFeU4KHTnGI7sO/xu3y8uvwFfo4aWPSRu36+041SOAjIK7m9I+ppN1JwrKomt9jNE1OL713YAkei+jL+R7hGMZa9KfT/qehM3V7OsOHgrUY4LLrGKmVOz03lUPL+I="
after_success:
    gulp deploy --user $FTP_USER --password $FTP_PASSWORD