# Bericht bij verbreken NodeMCU Serre
- id: '1533553411857'
  alias: Bericht bij verbreken NodeMCU Serre
  trigger:
  - entity_id: binary_sensor.serre_status
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Verbinding met NodeMCU Serre verbroken
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden NodeMCU Serre
- id: '1533553548849'
  alias: Bericht bij verbinden NodeMCU Serre
  trigger:
  - entity_id: binary_sensor.serre_status
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: NodeMCU Serre verbonden
    service: notify.ios_iphone_jeffry
# Meer dan 45°C in de serre
- id: '1533553672666'
  alias: Meer dan 45°C in de serre
  trigger:
  - above: '45'
    entity_id: sensor.temperatuur_serre_dallas
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.notify_serre_temp
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.temperatuur_serre_dallas
    below: '85'
  action:
  - data:
      message: Het is warmer dan 45°C
    service: notify.ios_iphone_jeffry
  - data:
      entity_id: input_boolean.notify_serre_temp
    service: input_boolean.turn_on
# Waarschuwing bij een grondvochtigheid van minder dan 50%
# - id: '1533553759096'
#   alias: Waarschuwing bij een grondvochtigheid van minder dan 50%
#   trigger:
#   - below: '50'
#     entity_id: sensor.serre_soil
#     platform: numeric_state
#   condition:
#   - condition: state
#     entity_id: input_boolean.notify_serre_soil
#     state: 'off'
#   action:
#   - data:
#       message: De grondvochtigheid is lager dan 50%
#     service: notify.ios_iphone_jeffry
#   - alias: ''
#     data:
#       entity_id: input_boolean.notify_serre_soil
#     service: input_boolean.turn_on
# Automatisch serre input booleans op off zetten
- id: '1533643226682'
  alias: Automatisch serre input booleans op off zetten
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: notify_serre_temp
    service: input_boolean.turn_off
  - data:
      entity_id: notify_serre_temp
    service: input_boolean.turn_off
# Bezoek
- id: '1535032148593'
  alias: Test aanwezigheid
  trigger:
  - entity_id: device_tracker.galaxy_s8_kevin
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: BEZOEK!
    service: notify.ios_iphone_jeffry
# Bericht dat pierre thuis is
- id: '1535099169538'
  alias: Pierre thuis
  trigger:
  - entity_id: device_tracker.galaxys8_pierre
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Pierre is thuis
    service: notify.ios_iphone_jeffry
# Bericht dat Pierre water aan het geven is
- id: '1535099383621'
  alias: Bericht dat Pierre water aan het geven is
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''device_tracker.galaxys8_pierre'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  condition: []
  action:
  - data:
      message: Pierre is water aan het geven
    service: notify.ios_iphone_jeffry
# Verlichting aan bij valavond indien iemand thuis
- id: '1536510294355'
  alias: Verlichting aan bij valavond indien iemand thuis
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - data:
      entity_id: switch.bol_living
    service: switch.turn_on
  - data:
      message: Verlichting is aan
    service: notify.ios_iphone_jeffry
# Alle verlichting uitschakelen om 00:00 indien TV ook uit
- id: '1536510427914'
  alias: Verlichting uit om 00h00
  trigger:
  - at: 00:00
    platform: time
  condition:
  - condition: state
    entity_id: group.lights
    state: 'on'
  - condition: state
    entity_id: media_player.tv_living
    state: 'off'
  action:
  - data:
      entity_id: group.lights
    service: light.turn_off
  - data:
      entity_id: light.verlichting_voortuin
    service: light.turn_off
  - data:
      entity_id: switch.bol_living
    service: light.turn_off
  - data:
      message: Verlichting uitgeschakeld om middernacht
    service: notify.ios_iphone_jeffry
# Verlichting aan 's morgens'
- id: '1536510555331'
  alias: Verlichting aan 's morgens
  trigger:
  - at: 06:20
    platform: time
  condition:
  - below: '3.5'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - data:
      entity_id: light.tuinhuis_buiten
    service: light.turn_on
  - data:
      entity_id: light.verlichting_voortuin
    service: light.turn_on
  - data:
      entity_id: switch.bol_living
    service: light.turn_on
  - data:
      message: Verlichting aangeschakeld 's morgens
    service: notify.ios_iphone_jeffry
# Verlichting uit 's morgens
- id: '1536510724699'
  alias: Verlichting uit 's morgens
  trigger:
  - event: sunrise
    offset: +00:15:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.lights
    state: 'on'
  action:
  - data:
      entity_id: group.lights
    service: light.turn_off
  - data:
      entity_id: light.verlichting_voortuin
    service: light.turn_off
  - data:
      entity_id: switch.bol_living
    service: light.turn_off
  - data:
      message: Verlichting uitgeschakeld 's morgens
    service: notify.ios_iphone_jeffry
# Bericht bij verbreken NodeMCU TV verlichting
- id: '1533553411877'
  alias: Bericht bij verbreken NodeMCU TV verlichting
  trigger:
  - entity_id: binary_sensor.nodemcu_tv_verlichting
    from: online
    platform: state
    to: offline
  condition: []
  action:
  - data:
      message: Verbinding met NodeMCU TV Verlichting verbroken
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden NodeMCU TV verlichting
- id: '1533553411878'
  alias: Waarschuwing bij verbinden NodeMCU TV verlichting
  trigger:
  - entity_id: binary_sensor.nodemcu_tv_verlichting
    from: offline
    platform: state
    to: online
  condition: []
  action:
  - data:
      message: NodeMCU TV Verlichting verbonden
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden NodeMCU Tuinhuis
- id: '1533553411879'
  alias: Waarschuwing bij verbinden NodeMCU Tuinhuis
  trigger:
  - entity_id: binary_sensor.nodemcu_tuinhuis
    from: offline
    platform: state
    to: online
  condition: []
  action:
  - data:
      message: NodeMCU Tuinhuis verbonden
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden verloren NodeMCU Tuinhuis
- id: '1533553411879'
  alias: Waarschuwing bij NodeMCU Tuinhuis verbroken
  trigger:
  - entity_id: binary_sensor.nodemcu_tuinhuis
    from: online
    platform: state
    to: offline
  condition: []
  action:
  - data:
      message: NodeMCU Tuinhuis verbroken
    service: notify.ios_iphone_jeffry
# Verlichting uit indien TV uit na 22h00
- id: '2000000000000'
  alias: Verlichting uit indien TV uit na 22h00
  trigger:
  - platform: state
    entity_id: media_player.tv_living
    from: playing
    to: 'off'
  condition:
  - condition: time
    after: '22:00:00'
  - condition: state
    entity_id: group.lights
    state: 'on'
  action:
  - data:
      message: Verlichting wordt achter 10 minuut uitgeschakeld
    service: notify.ios_iphone_jeffry
  # blink light 2 times
  - data:
      entity_id: light.tv_living
    service: light.turn_off
  - delay: 00:00:01
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.tv_living
    service: light.turn_off
  - delay: 00:00:01
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - delay: 00:09:00
  # blink light 2 times for last minute
  - data:
      entity_id: light.tv_living
    service: light.turn_off
  - delay: 00:00:01
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.tv_living
    service: light.turn_off
  - delay: 00:00:01
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - delay: 00:01:00
  - data:
      entity_id: light.tv_living
    service: light.turn_off
  - data:
      message: Verlichting uitgeschakeld omdat het na 22h00 is en de tv gaat uit
    service: notify.ios_iphone_jeffry
# Verlichting aan indien iemand thuis komt na zonsondergang
- id: '2000000000001'
  alias: Verlichting aan indien iemand thuis komt na zonsondergang
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: home
  condition:
  - after: sunset
    after_offset: -00:30:00
    condition: sun
  - condition: state
    entity_id: light.tv_living
    state: 'off'
  action:
  - data:
      entity_id: light.tv_living
    service: light.turn_on
  - data:
      entity_id: light.tuinhuis_buiten
    service: light.turn_on
  - data:
      entity_id: switch.bol_living
    service: switch.turn_on
  - data:
      message: Verlichting aangeschakeld omdat iemand na zonsondergang thuis komt
    service: notify.ios_iphone_jeffry
# bericht bij vertrek
- id: '2000000000002'
  alias: bericht bij vertrek
  trigger:
  - entity_id: device_tracker.iphone_van_katja
    platform: state
    from: Kevin
  condition: []
  action:
  - data:
      message: vertrokken
    service: notify.ios_iphone_jeffry
# Bericht bij veranderen referte index C
- id: '2000000000003'
  alias: Bericht bij veranderen referte index C
  trigger:
  - entity_id: sensor.referteindexc
    platform: state
  action:
  - service: notify.ios_iphone_jeffry
    data_template:
      message: Referte index C is aangepast naar {{ states("sensor.referteindexc")}}%
# Buitenlicht tuinhuis aan indien iemand verbonden met AP tuinhuis
- id: '2000000000004'
  alias: Buitenlicht tuinhuis aan indien iemand verbonden met AP tuinhuis
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''device_tracker.galaxys8_pierre'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''device_tracker.iphone_van_katja'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''device_tracker.iphone_jeffry'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  condition:
  - below: '3.5'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: light.tuinhuis_tuin
    service: light.turn_on
  - data:
      message: Verlichting tuinhuis aan omdat iemand verbonden is met de AP tuinhuis
    service: notify.ios_iphone_jeffry
# Buitenlicht tuinhuis uit indien iemand verbroken met AP tuinhuis
- id: '2000000000005'
  alias: Buitenlicht tuinhuis uit indien iemand verbroken met AP tuinhuis
  trigger:
  - platform: template
    value_template: '{{ not is_state_attr(''device_tracker.galaxys8_pierre'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  - platform: template
    value_template: '{{ not is_state_attr(''device_tracker.iphone_van_katja'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  - platform: template
    value_template: '{{ not is_state_attr(''device_tracker.iphone_jeffry'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  condition:
  - below: '3.5'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: light.tuinhuis_tuin
    service: light.turn_off
  - data:
      message: Verlichting tuinhuis uit omdat iemand verbroken is met de AP tuinhuis
    service: notify.ios_iphone_jeffry
# Waarschuwing indien water van de kippen onder 0.5°C gaat
- id: '2000000000006'
  alias: Waarschuwing indien water van de kippen onder 0.5 graden gaat
  trigger:
  - platform: numeric_state
    entity_id: sensor.kippen_water_temperatuur
    below: '0.5'
  action:
  - data:
      message: Temperatuur van het water van de kippen is beneden 0.5°C
    service: notify.ios_iphone_jeffry
# Bericht wanneer er een update is
- id: '2000000000007'
  alias: 'Bericht wanneer er een update is'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: 'Er is een update voor Home-assistant beschikbaar.'
# Bericht bij verbinden NodeMCU Kippen
- id: '2000000000008'
  alias: Waarschuwing bij verbinden NodeMCU Kippen
  trigger:
  - entity_id: binary_sensor.nodemcu_kippen
    from: offline
    platform: state
    to: online
  condition: []
  action:
  - data:
      message: NodeMCU Kippen verbonden
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden verloren NodeMCU Tuinhuis
- id: '2000000000009'
  alias: Waarschuwing bij NodeMCU Kippen verbroken
  trigger:
  - entity_id: binary_sensor.nodemcu_Kippen
    from: online
    platform: state
    to: offline
  condition: []
  action:
  - data:
      message: NodeMCU Kippen verbroken
    service: notify.ios_iphone_jeffry
# Bericht bij verbinding verbroken NodeMCU Living_bol
- id: '2000000000010'
  alias: Bericht bij verbinding verbroken NodeMCU Living_bol
  trigger:
  - entity_id: binary_sensor.nodemcu_living_bol
    from: online
    platform: state
    to: offline
  action:
  - data:
      message: NodeMCU Living bol verbroken
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden NodeMCU Living_bol
- id: '2000000000011'
  alias: Waarschuwing bij verbinden NodeMCU Living_bol
  trigger:
  - entity_id: binary_sensor.nodemcu_living_bol
    from: offline
    platform: state
    to: online
  action:
  - data:
      message: NodeMCU Living bol verbonden
    service: notify.ios_iphone_jeffry
# Katja verbroken met AP tuinhuis
- id: '20000000000012'
  alias: Bericht Katja verbroken met AP tuinhuis
  trigger:
  - platform: template
    value_template: '{{ not is_state_attr(''device_tracker.iphone_van_katja'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  action:
  - data:
      message: Verlichting tuinhuis uit omdat Katja verbroken is met de AP tuinhuis
    service: notify.ios_iphone_jeffry
# Jeffry verbroken met AP tuinhuis
- id: '20000000000013'
  alias: Bericht Jeffry verbroken met AP tuinhuis
  trigger:
  - platform: template
    value_template: '{{ not is_state_attr(''device_tracker.iphone_jeffry'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  action:
  - data:
      message: Verlichting tuinhuis uit omdat Jeffry verbroken is met de AP tuinhuis
    service: notify.ios_iphone_jeffry
# Pierre verbroken met AP tuinhuis
- id: '20000000000014'
  alias: Bericht Pierre verbroken met AP tuinhuis
  trigger:
  - platform: template
    value_template: '{{ not is_state_attr(''device_tracker.galaxys8_pierre'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  action:
  - data:
      message: Verlichting tuinhuis uit omdat pierre verbroken is met de AP tuinhuis
    service: notify.ios_iphone_jeffry
# bericht bij aankomst
- id: '2000000000015'
  alias: bericht bij aankomst
  trigger:
  - entity_id: device_tracker.iphone_van_katja
    platform: state
    to: Kevin
  - entity_id: device_tracker.iphone_van_katja
    platform: state
    to: Kerakris
  condition: []
  action:
  - data:
      message: aangekomen
    service: notify.ios_iphone_jeffry
# Weersvoorspelling versturen 's morgens
- id: '2000000000016'
  alias: Weersvoorspelling Komende dag
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - service: notify.ios_iphone_jeffry
    data:
      message: '{{ states("sensor.darksky") }}'
# Bericht bij verbinden NodeMCU Energy meter
- id: '2000000000017'
  alias: Waarschuwing bij verbinden NodeMCU Energy meter
  trigger:
  - entity_id: binary_sensor.energy_meter_status_2
    from: "off"
    platform: state
    to: "on"
  condition: []
  action:
  - data:
      message: NodeMCU Energy meter verbonden
    service: notify.ios_iphone_jeffry
# Bericht bij verbinden verloren NodeMCU Energy meter
- id: '2000000000018'
  alias: Waarschuwing bij NodeMCU Energy meter verbroken
  trigger:
  - entity_id: binary_sensor.energy_meter_status_2
    from: "on"
    platform: state
    to: "off"
  condition: []
  action:
  - data:
      message: NodeMCU Energy meter verbroken
    service: notify.ios_iphone_jeffry
# buitenverlichting aan bij valavond
- id: '2000000000019'
  alias: buitenverlichting aan bij valavond
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.tuinhuis_buiten
    service: light.turn_on
  - data:
      entity_id: light.verlichting_voortuin
    service: light.turn_on
  - data:
      message: buitenverlichting is aan
    service: notify.ios_iphone_jeffry