- id: '1533553411857'
  alias: NodeMCU Serre disconnected message
  trigger:
  - entity_id: binary_sensor.nodemcu_serre
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Verbinding met NodeMCU Serre verbroken
    service: notify.ios_iphone_jeffry
- id: '1533553548849'
  alias: NodeMCU Serre connected message
  trigger:
  - entity_id: binary_sensor.nodemcu_serre
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: NodeMCU Serre verbonden
    service: notify.ios_iphone_jeffry
- id: '1533553672666'
  alias: Over 45°C in greenhouse
  trigger:
  - above: '45'
    entity_id: sensor.serre_temp
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.notify_serre_temp
    state: 'off'
  action:
  - data:
      message: Het is warmer dan 45°C
    service: notify.ios_iphone_jeffry
  - alias: ''
    data:
      entity_id: input_boolean.notify_serre_temp
    service: input_boolean.turn_on
- id: '1533553759096'
  alias: Waarschuwing bij een grondvochtigheid van minder dan 50%
  trigger:
  - below: '50'
    entity_id: sensor.serre_soil
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.notify_serre_soil
    state: 'off'
  action:
  - data:
      message: De grondvochtigheid is lager dan 50%
    service: notify.ios_iphone_jeffry
  - alias: ''
    data:
      entity_id: input_boolean.notify_serre_soil
    service: input_boolean.turn_on
- id: '1533643226682'
  alias: Automatisch serre input booleans op off zetten
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: notify_serre_temp
    service: input_boolean.turn_off
  - data:
      entity_id: notify_serre_temp
    service: input_boolean.turn_off
- id: '1535032148593'
  alias: Test aanwezigheid
  trigger:
  - entity_id: device_tracker.galaxy_s8_kevin
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: BEZOEK!
    service: notify.ios_iphone_jeffry
- id: '1535099169538'
  alias: Pierre thuis
  trigger:
  - entity_id: device_tracker.galaxys8_pierre
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Pierre is thuis
    service: notify.ios_iphone_jeffry
- id: '1535099383621'
  alias: Pierre water aan het geven
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''device_tracker.galaxys8_pierre'', ''ap_mac'',
      ''80:2a:a8:59:e0:2e'') }}'
  condition: []
  action:
  - data:
      message: Pierre is water aan het geven
    service: notify.ios_iphone_jeffry
- id: '1536510294355'
  alias: Verlichting aan bij valavond indien iemand thuis
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data:
      entity_id: switch.licht_tv_living
    service: switch.turn_on
  - data:
      message: Verlichting is aan
    service: notify.ios_iphone_jeffry
- id: '1536510427914'
  alias: Verlichting uit om 00h00
  trigger:
  - at: 00:00
    platform: time
  condition:
  - condition: state
    entity_id: switch.licht_tv_living
    state: 'on'
  - condition: state
    entity_id: media_player.tv_living
    state: 'off'
  action:
  - data:
      entity_id: switch.licht_tv_living
    service: switch.turn_off
  - data:
      message: Verlichting uitgeschakeld om middernacht
    service: notify.ios_iphone_jeffry
- id: '1536510555331'
  alias: Verlichting aan 's morgens
  trigger:
  - at: 06:20
    platform: time
  condition:
  - below: '3.5'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: switch.licht_tv_living
    service: switch.turn_on
  - data:
      message: Verlichting aangeschakeld 's morgens
    service: notify.ios_iphone_jeffry
- id: '1536510724699'
  alias: Verlichting uit 's morgens
  trigger:
  - event: sunrise
    offset: +00:15:00
    platform: sun
  condition:
  - condition: state
    entity_id: switch.licht_tv_living
    state: 'on'
  action:
  - alias: ''
    data:
      entity_id: switch.licht_tv_living
    service: switch.turn_off
  - data:
      message: Verlichting uitgeschakeld 's morgens
    service: notify.ios_iphone_jeffry
- id: '1533553411877'
  alias: Waarschuwing bij verbreken NodeMCU TV verlichting
  trigger:
  - entity_id: binary_sensor.nodemcu_tv_verlichting
    from: online
    platform: state
    to: offline
  condition: []
  action:
  - data:
      message: Verbinding met NodeMCU TV Verlichting verbroken
    service: notify.ios_iphone_jeffry
- id: '1533553411878'
  alias: Waarschuwing bij verbinden NodeMCU TV verlichting
  trigger:
  - entity_id: binary_sensor.nodemcu_tv_verlichting
    from: offline
    platform: state
    to: online
  condition: []
  action:
  - data:
      message: NodeMCU TV Verlichting verbonden
    service: notify.ios_iphone_jeffry
- id: '2000000000000'
  alias: Verlichting uit indien TV uit na 22h00
  trigger:
  - platform: state
    entity_id: media_player.tv_living
    from: playing
    to: 'off'
  condition:
  - condition: time
    after: '22:00:00'
  - condition: state
    entity_id: switch.licht_tv_living
    state: 'on'
  action:
  - data:
      message: Verlichting wordt achter 5 minuut uitgeschakeld
    service: notify.ios_iphone_jeffry
  - delay: 00:05:00
  - data:
      entity_id: switch.licht_tv_living
    service: switch.turn_off
  - data:
      message: Verlichting uitgeschakeld omdat het na 22h00 is en de tv gaat uit
    service: notify.ios_iphone_jeffry
- id: '2000000000001'
  alias: Verlichting aan indien iemand thuis komt na zonsondergang
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: home
  condition:
  - after: sunset
    after_offset: -00:30:00
    condition: sun
  - condition: state
    entity_id: switch.licht_tv_living
    state: 'off'
  action:
  - data:
      message: Verlichting aangeschakeld omdat iemand na 22h00 thuis komt
    service: notify.ios_iphone_jeffry
- id: '2000000000002'
  alias: bericht bij vertrek k
  trigger:
  - entity_id: device_tracker.iphone_van_katja
    platform: state
    from: Kevin
  condition:
  action:
  - data:
      message: vertrokken
    service: notify.ios_iphone_jeffry
- id: '2000000000003'
  alias: Bericht bij veranderen referte index C
  trigger:
  - entity_id: sensor.referteindexc
    platform: state
  action:
  - service: notify.ios_iphone_jeffry
    data_template:
      message: >
        Referte index C is aangepast naar {{ states("sensor.referteindexc")}}%