homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  javascript_version: auto

# Enables configuration UI
config:

system_health:

ios:

lovelace:
  mode: yaml

http:
  api_password: !secret http_password
  base_url: !secret http_baseurl
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24

updater:
  reporting: no

recorder:
  purge_keep_days: 30
  db_url: !secret mysql_db_url
  

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

wake_on_lan: # enables `wake_on_lan` domain

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids: !secret telegram_allowed_chat_ids

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret notify_telegram_chat_id

homekit:
  filter:
    include_domains:
      - switch
      - light

google_assistant: 
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  entity_config:
    light.tv_living:
      name: Tv verlichting
      aliases:
        - tv light
        - tv verlichting
        - kerstboom
    light.kippen:
      name: Licht kippen
      aliases:
        - kippen verlichting

# homeconnect:
#   client_id: !secret homeconnect_clientid
#   client_secret: !secret homeconnect_clientsecret

nest:
  client_id: 667684cb-7baf-4fe7-a6e7-5188b6a50ff9
  client_secret: 25oHS1O9B0X7O44Mo2AqlRnub
  # sensors:
  #   monitored_conditions:
  #     - 'humidity'
  #     - 'operation_mode'
  #     - 'temperature'

tuya:
  username: !secret tuya__username
  password: !secret tuya__password
  country_code: 32

cast: !include config/cast.yaml
mqtt: !include config/mqtt.yaml
input_boolean: !include config/input_boolean.yaml
#sabnzbd: !include config/sabnzbd.yaml
camera: !include config/cameras.yaml
zone: !include config/zones.yaml
media_player: !include config/media_players.yaml
binary_sensor: !include config/binary_sensor.yaml
history_graph: !include config/history_graph.yaml
device_tracker: !include config/device_tracker.yaml
sensor: !include config/sensors.yaml
switch: !include config/switch.yaml
influxdb: !include config/influxdb.yaml
light: !include config/light.yaml

group: !include groups.yaml
automation: !include automations.yaml
#automation: !include_dir_merge_list configuration/automations/
script: !include scripts.yaml