resources:
  - url: /local/bignumber-card.js?v=1
    type: js
  - url: /local/surveillance-card.js?v=1
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module
  - url: /local/card-tools.js?v=1
    type: js
  - url: /local/useful-markdown-card.js?v=1
    type: js

title: Langstraat 60

views:
  - title: Dashboard
    icon: mdi:home-assistant
    id: dashboard
    cards:
      - type: custom:useful-markdown-card
        content: >
          # Weersvoorspelling

          [[ sensor.darksky ]]
      - type: entities
        title: verlichting
        entities:
          - light.tv_living
          - light.bol_living
          - light.tuinhuis_buiten
          - light.kippen
          - light.tuinhuis_binnen
          - light.tuinhuis_tuin
          - light.tuinhuis_werkbank
      - type: sensor
        entity: sensor.stroom_2
        name: Huidig algemeen verbruik
        icon: mdi:flash
        graph: line
        unit: W
        detail: 2
        hours_to_show: 4
      - type: sensor
        entity: sensor.total_daily_energy_2
        name: Daily energy
        icon: mdi:counter
        graph: line
        detail: 2
        hours_to_show: 4
      - type: sensor
        entity: sensor.water
        name: Water flow
        icon: mdi:counter
        graph: line
        detail: 2
        hours_to_show: 4
      - type: custom:bignumber-card
        title: Referte index C
        entity: sensor.referteindexc
        min: -3
        max: 6.20
        from: left
        severity:
          - value: -0.19
            style: 'var(--label-badge-green)'
          - value: 3.2
            style: 'var(--label-badge-yellow)'
          - value: 6.2
            style: 'var(--label-badge-red)'
      - type: custom:mini-graph-card
        name: Serre
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 0
        line_color_below: '#0000ff'
        line_value_above: 40
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.temperatuur_serre_dallas
      - type: custom:mini-graph-card
        name: Tuinhuis
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 0
        line_color_below: '#0000ff'
        line_value_above: 30
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.tuinhuis_temperatuur_buiten
      - type: custom:mini-graph-card
        name: Gang
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 15
        line_color_below: '#0000ff'
        line_value_above: 25
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.temperature_bureau
      - type: custom:mini-graph-card
        name: Temperatuur living
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 20
        line_color_below: '#0000ff'
        line_value_above: 25
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.living_temperatuur
      - type: custom:mini-graph-card
        name: Bureau
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 20
        line_color_below: '#0000ff'
        line_value_above: 25
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.temperatuur_bureau
      - type: custom:mini-graph-card
        name: Kippen water
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 0
        line_color_below: '#0000ff'
        line_value_above: 30
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.kippen_water_temperatuur
      - type: custom:mini-graph-card
        name: Serre
        icon: mdi:thermometer
        unit: °C
        detail: 2
        hours_to_show: 24
        line_color: '#167f01'
        line_value_below: 0
        line_color_below: '#0000ff'
        line_value_above: 40
        line_color_above: '#ff0000'
        labels: true
        entity: sensor.temperatuur_serre
      - type: glance
        title: Serre
        entities:
          - sensor.temperatuur_serre_dallas
          - sensor.serre_humidity_dht11
          - sensor.serre_temperature_dht11
      - type: glance
        title: Buienradar
        columns: 2
        entities:
          - sensor.elen_temperature_2
          - sensor.elen_precipitation_2
          - sensor.elen_precipitation_forecast_average
          - sensor.elen_irradiance
      # - type: glance
      #   title: Diesel prijzen
      #   columns: 3
      #   entities:
      #     - sensor.sbhavertdiesel
      #     - sensor.essoselfkantdiesel
      #     - sensor.shellselfkantdiesel
      #     - sensor.haanroosterendiesel
      #     - sensor.gabrielsdilsendiesel
      #     - sensor.tinqmauritslaandiesel
      #     - sensor.tinqjosklijnenlaandiesel
      #     - sensor.totalelendiesel
      - type: glance
        title: Aanwezigheid
        entities:
          - device_tracker.iphone_jeffry
          - device_tracker.iphone_van_katja
      # - type: entities
      #   title: Vaatwasser
      #   entities:
      #     - binary_sensor.vaatwasser_door
      #     - sensor.vaatwasser_program_progress
      #     - sensor.vaatwasser_remaining_program_time
      #     - switch.vaatwasser
      #     - switch.vaatwasser_program_auto1
      #     - switch.vaatwasser_program_auto2
      #     - switch.vaatwasser_program_auto3
      #     - switch.vaatwasser_program_eco50
      #     - switch.vaatwasser_program_quick45
  - title: Media players
    icon: mdi:television
    id: mediaplayers
    cards:
      - type: media-control
        entity: media_player.tv_living
      - type: media-control
        entity: media_player.ccliving
      - type: media-control
        entity: media_player.cckinderen
  - title: Verbruik
    icon: mdi:power-socket-eu
    id: verbruik
    cards:
      - type: sensor
        name: Huidig verbruik bol living 
        icon: mdi:flash
        graph: line
        unit: Watt
        detail: 2
        hours_to_show: 24
        entity: sensor.bol_living_watt
      - type: sensor
        entity: sensor.stroom_2
        name: Huidig algemeen verbruik
        icon: mdi:flash
        graph: line
        unit: W
        detail: 2
        hours_to_show: 4
      - type: sensor
        entity: sensor.total_daily_energy_2
        name: Daily energy
        icon: mdi:counter
        graph: line
        detail: 2
        hours_to_show: 4
      - type: sensor
        entity: sensor.water
        name: Water flow
        icon: mdi:counter
        graph: line
        detail: 2
        hours_to_show: 4
      - type: glance
        title: WiFi signal
        entities:
          - sensor.wifi_signal_sensor
          - sensor.wifi_signal_sensor_2
      - type: entities
        title: Interne led
        show_header_toggle: false
        entities:
          - switch.switch_test_2
      - type: entity-button
        entity: switch.switch_test_2
        name: "interne led"
        tap_action:
          action: toggle
  - title: Weer
    icon: mdi:weather-partlycloudy
    id: weer
    cards:
      - type: glance
        title: Weer
        columns: 3
        entities:
          - sensor.bureau
          - sensor.elen_temperature_2
          - sensor.tuinhuis_temperatuur_binnen
          - sensor.tuinhuis_temperatuur_buiten
          - sensor.kippen_buiten_temperatuur
          - sensor.kippen_water_temperatuur
          - sensor.serre_temp
          - sensor.serre_humidity
          - sensor.serre_soil
          - sensor.elen_precipitation_2
          - sensor.elen_precipitation_forecast_average
          - sensor.elen_irradiance
      - type: history-graph
        title: Binnen temperatuur
        entities:
          - sensor.bureau
          - sensor.living_temperatuur
      - type: history-graph
        title: Buiten temperatuur
        entities:
          - sensor.elen_temperature_2
          - sensor.tuinhuis_temperatuur_binnen
          - sensor.tuinhuis_temperatuur_buiten
          - sensor.kippen_buiten_temperatuur
          - sensor.kippen_water_temperatuur
          - sensor.serre_temp
      - type: history-graph
        title: Regen
        entities:
          - sensor.elen_precipitation_2
          - sensor.elen_precipitation_forecast_average
      - type: history-graph
        title: Zon
        entities:
          - sensor.elen_irradiance
  - title: CCTV
    icon: mdi:cctv
    id: cctv
    panel: true
    cards:
      - type: custom:surveillance-card
        thumb_interval: 15
        update_interval: 2
        cameras:
          - entity: camera.oprit
          - entity: camera.tuinhuis
  - title: Status
    icon: mdi:power-plug
    id: status
    cards:
      - type: entities
        title: NodeMCU
        show_header_toggle: false
        entities:
          - binary_sensor.serre_status
          - binary_sensor.energy_meter_status_2
          - binary_sensor.nodemcu_tv_verlichting
          - binary_sensor.nodemcu_kippen
          - binary_sensor.nodemcu_tuinhuis
          - binary_sensor.nodemcu_living_bol
      - type: entities
        title: NodeRED
        show_header_toggle: false
        entities:
          - binary_sensor.nodered_docker
          - binary_sensor.nodered_castleblack
  # - title: Brandstofprijzen
  #   icon: mdi:gas-station
  #   id: brandstofprijzen
  #   cards:
  #     - type: sensor
  #       name: SB Havert (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.sbhavertdiesel
  #     - type: sensor
  #       name: ESSO Selfkant (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.essoselfkantdiesel
  #     - type: sensor
  #       name: SHELL Selfkant (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.shellselfkantdiesel
  #     - type: sensor
  #       name: HAAN Roosteren (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.haanroosterendiesel
  #     - type: sensor
  #       name: GABRIELS Dilsen (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.gabrielsdilsendiesel
  #     - type: sensor
  #       name: TINQ Mauritslaan (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.tinqmauritslaandiesel
  #     - type: sensor
  #       name: TINQ Josklijnenlaan (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.tinqjosklijnenlaandiesel
  #     - type: sensor
  #       name: TOTAL Elen (diesel)
  #       icon: mdi:gas-station
  #       graph: line
  #       unit: €
  #       detail: 2
  #       hours_to_show: 48
  #       entity: sensor.totalelendiesel
  - title: Automations
    icon: mdi:home-automation
    cards:
      - type: entities
        title: Tuinhuis
        show_header_toggle: false
        entities:
          - automation.buitenlicht_tuinhuis_aan_indien_iemand_verbonden_met_ap_tuinhuis
          - automation.buitenlicht_tuinhuis_uit_indien_iemand_verbroken_met_ap_tuinhuis
      - type: entities
        title: Verlichting
        show_header_toggle: false
        entities:
          - automation.buitenlicht_tuinhuis_aan_indien_iemand_verbonden_met_ap_tuinhuis
          - automation.buitenlicht_tuinhuis_uit_indien_iemand_verbroken_met_ap_tuinhuis
          - automation.verlichting_aan_bij_valavond_indien_iemand_thuis
          - automation.verlichting_aan_indien_iemand_thuis_komt_na_zonsondergang
          - automation.verlichting_aan_s_morgens
          - automation.verlichting_uit_indien_tv_uit_na_22h00
          - automation.verlichting_uit_om_00h00
          - automation.verlichting_uit_s_morgens
      - type: entities
        title: Connectie status berichten
        show_header_toggle: false
        entities:
          - automation.bericht_bij_verbinden_nodemcu_serre
          - automation.bericht_bij_verbreken_nodemcu_serre
          - automation.bericht_bij_verbreken_nodemcu_tv_verlichting
          - automation.waarschuwing_bij_nodemcu_tuinhuis_verbroken
          - automation.waarschuwing_bij_verbinden_nodemcu_tuinhuis
          - automation.waarschuwing_bij_verbinden_nodemcu_tv_verlichting
          - automation.waarschuwing_bij_verbinden_nodemcu_kippen
          - automation.waarschuwing_bij_nodemcu_kippen_verbroken
          - automation.bericht_bij_verbinding_verbroken_nodemcu_living_bol
          - automation.waarschuwing_bij_verbinden_nodemcu_living_bol
      - type: entities
        title: Temperatuur berichten
        show_header_toggle: false
        entities:
          - automation.waarschuwing_indien_water_van_de_kippen_onder_0_5_graden_gaat
      - type: entities
        title: Tuinhuis connectie met AP
        show_header_toggle: false
        entities:
          - automation.buitenlicht_tuinhuis_aan_indien_iemand_verbonden_met_ap_tuinhuis
          - automation.buitenlicht_tuinhuis_uit_indien_iemand_verbroken_met_ap_tuinhuis
          - automation.bericht_katja_verbroken_met_ap_tuinhuis
          - automation.bericht_jeffry_verbroken_met_ap_tuinhuis
          - automation.bericht_pierre_verbroken_met_ap_tuinhuis
      - type: entities
        title: Tracking
        show_header_toggle: false
        entities:
          - automation.bericht_bij_vertrek
          - automation.bericht_bij_aankomst
          - automation.test_aanwezigheid
  - title: Docker
    icon: mdi:docker
    cards:
      - type: entities
        title: Synology
        show_header_toggle: false
        entities:
          - switch.hadockermon_grafana
          - switch.hadockermon_ha_dockermon
          - switch.hadockermon_home_assistant
          - switch.hadockermon_influxdb
          - switch.hadockermon_mqtt
          - switch.hadockermon_nextcloud
          - switch.hadockermon_nodered
          - switch.hadockermon_phpmyadmin
          - switch.hadockermon_sabnzbd
          - switch.hadockermon_sickrage
          - switch.hadockermon_sonarr
          - switch.hadockermon_spotweb
          - switch.hadockermon_spotweb_db
          - switch.hadockermon_transmission
          - switch.hadockermon_unifi
          - switch.hadockermon_watchtower