- platform: mqtt
  name: "NodeRED Docker"
  state_topic: "state/nodereddocker"
  qos: 0
  payload_on: "On"
  payload_off: "Off"
  device_class: connectivity
- platform: mqtt
  name: "NodeRED CastleBlack"
  state_topic: "state/noderedcastleblack"
  qos: 0
  payload_on: "On"
  payload_off: "Off"
  device_class: connectivity
- platform: mqtt
  name: "NodeMCU Serre"
  state_topic: "state/serre"
  qos: 0
  payload_on: "On"
  payload_off: "Off"
  device_class: connectivity
- platform: mqtt
  name: "NodeMCU Tv Verlichting"
  state_topic: "pstvliving/state"
  qos: 0
  payload_on: "online"
  payload_off: "Offline"
  device_class: connectivity
- platform: mqtt
  name: "NodeMCU Kippen"
  state_topic: "powerswitch/chicken/state"
  qos: 0
  payload_on: "online"
  payload_off: "Offline"
  device_class: connectivity
- platform: mqtt
  name: "NodeMCU Shed"
  state_topic: "powerswitch/shed/state"
  qos: 0
  payload_on: "online"
  payload_off: "offline"
  device_class: connectivity