- platform: mqtt
  name: "NodeRED Docker"
  state_topic: "state/nodereddocker"
  qos: 0
  payload_on: "On"
  payload_off: "Off"
  device_class: connectivity
- platform: mqtt
  name: "NodeRED CastleBlack"
  state_topic: "state/noderedcastleblack"
  qos: 0
  payload_on: "On"
  payload_off: "Off"
  device_class: connectivity
- platform: mqtt
  name: "NodeMCU Serre"
  state_topic: "state/serre"
  qos: 0
  payload_on: "On"
  payload_off: "Off"
  device_class: connectivity