- platform: generic
  name: Oprit
  still_image_url: !secret camera_pierre_oprit_still_image_url
- platform: generic
  name: Tuinhuis
  still_image_url: !secret camera_pierre_tuinhuis_still_image_url
#- platform: uvc
#  nvr: pierrevanoijen.synology.me
#  key: !secret camera_pierre_api_key
#  password: !secret camera_pierre_password