- platform: mqtt
  name: "TV living"
  command_topic: "pstvliving/cmd"
  state_topic: "pstvliving/relay/state"
  availability_topic: "pstvliving/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0
- platform: mqtt
  name: "Kippen"
  command_topic: "powerswitch/chicken/relay/cmd"
  state_topic: "powerswitch/chicken/relay/state"
  availability_topic: "powerswitch/chicken/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0
- platform: mqtt
  name: "Tuinhuis tuin"
  command_topic: "powerswitch/shed/relay/cmd/1"
  state_topic: "powerswitch/shed/relay/state/1"
  availability_topic: "powerswitch/shed/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0
- platform: mqtt
  name: "Tuinhuis buiten"
  state_topic: "powerswitch/shed/relay/state/2"
  command_topic: "powerswitch/shed/relay/cmd/2"
  availability_topic: "powerswitch/shed/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0
- platform: mqtt
  name: "Tuinhuis binnen"
  command_topic: "powerswitch/shed/relay/cmd/3"
  state_topic: "powerswitch/shed/relay/state/3"
  availability_topic: "powerswitch/shed/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0
- platform: mqtt
  name: "Tuinhuis werkbank"
  command_topic: "powerswitch/shed/relay/cmd/4"
  state_topic: "powerswitch/shed/relay/state/4"
  availability_topic: "powerswitch/shed/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0
- platform: mqtt
  name: "Tent"
  command_topic: "powerswitch/tent/relay/cmd/1"
  state_topic: "powerswitch/tent/relay/state/1"
  availability_topic: "powerswitch/tent/state"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  qos: 0