- platform: webostv
  host: !secret webostv_living_ip
  name: TV Living
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webostv_living_mac
- platform: plex
  entity_namespace: plex
  include_non_clients: true
  scan_interval: 5
  use_episode_art: true