broker: !secret mqtt_broker
port: !secret mqtt_port
username: !secret mqtt_username
password: !secret mqtt_password
birth_message:
  topic: 'state/hass'
  payload: 'online'
will_message:
  topic: 'state/hass'
  payload: 'offline'