- platform: buienradar
  #name: !secret buienradar_name
  latitude: !secret buienradar_latitude
  longitude: !secret buienradar_longitude
  monitored_conditions:
    - precipitation
    - temperature
    - precipitation_forecast_average
    - irradiance
- platform: mqtt
  state_topic: "temperatuur/value/2861641279995A6E"
  name: "bureau"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "serre/temp/dallas"
  name: "Serre temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "serre/humidity/dht11"
  name: "Serre humidity"
  icon: mdi:water-percent
  unit_of_measurement: "%"
  value_template: "{{ value | round(0) }}"
- platform: mqtt
  state_topic: "serre/soil/yl69"
  icon: mdi:water-percent
  name: "Serre soil"
  unit_of_measurement: "%"
  value_template: "{{ value | round(0) }}"
- platform: moon
- platform: darksky
  api_key: !secret darksky_api
  scan_interval:
    minutes: 5
  forecast:
    - 0
  language: nl
  monitored_conditions:
    - summary
    - icon
    - temperature
    - wind_speed
    - wind_gust
    - temperature_high
- platform: template
  sensors:
    darksky:
      friendly_name: "Weersvoorspelling darksky"
      value_template: >-
        {% set voorspelling = states.sensor.dark_sky_summary_0.state %}
        {% set temp = states.sensor.dark_sky_daytime_high_temperature_0.state %}
        {% set wind = states.sensor.dark_sky_wind_speed_0.state %}
        {% set gust = states.sensor.dark_sky_wind_gust_0.state %}
        "{{voorspelling}} Maximaal {{temp | round}}°C. Wind van {{wind | round}} tot {{gust | round}} km/u."
# - platform: scrape
#   name: sbhavertdiesel
#   friendly_name: SB in Havert
#   resource: https://www.clever-tanken.de/tankstelle_details/45777
#   select: "#main-content-fuel-price-list > div:nth-of-type(1) > div.price-box > div > span.price-field > span"
#   unit_of_measurement: "€/l"
#   value_template: '{{ value | float }}'
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: essoselfkantdiesel
#   friendly_name: ESSO in Selfkant
#   resource: https://www.clever-tanken.de/tankstelle_details/16935
#   select: "#main-content-fuel-price-list > div:nth-of-type(1) > div.price-box > div > span.price-field > span"
#   unit_of_measurement: "€/l"
#   value_template: '{{ value | float }}'
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: shellselfkantdiesel
#   friendly_name: SHELL in Selfkant
#   resource: https://www.clever-tanken.de/tankstelle_details/145148
#   select: "#main-content-fuel-price-list > div:nth-of-type(1) > div.price-box > div > span.price-field > span"
#   unit_of_measurement: "€/l"
#   value_template: '{{ value | float }}'
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: haanroosterendiesel
#   resource: https://www.unitedconsumers.com/tanken/informatie/tankstation.asp?StationId=440
#   select: "#accordionPrices > div:nth-of-type(2) > div:nth-of-type(2) > div > div > div > div:nth-of-type(2) > div:nth-of-type(2)"
#   value_template: "{{ value.split(' ')[1].replace(',', '.') | float }}"
#   unit_of_measurement: "€/l"
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: gabrielsdilsendiesel
#   resource: https://carbu.com/belgie//index.php/liste-stations-service/Diesel%20(B7)/Dilsen-Stokkem/3650/BE_li_653/113
#   select: "b#price_20204"
#   value_template: "{{ value.split(' ')[0].replace(',', '.') | float }}"
#   unit_of_measurement: "€/l"
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: tinqmauritslaandiesel
#   resource: http://www.tinq.nl/tankstation?id=299
#   select: "#station-prijzen > tbody > tr:nth-of-type(2) > td.literprijs"
#   value_template: "{{ value.split('\xa0')[1].replace(',', '.') | float }}"
#   unit_of_measurement: "€/l"
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: tinqjosklijnenlaandiesel
#   resource: http://www.tinq.nl/tankstation?id=60
#   select: "#station-prijzen > tbody > tr:nth-of-type(2) > td.literprijs"
#   value_template: "{{ value.split('\xa0')[1].replace(',', '.') | float }}"
#   unit_of_measurement: "€/l"
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: totalelendiesel
#   resource: https://carbu.com/belgie/index.php/station/total/dilsen-stokkem/3650/2984
#   select: ".carburants > div.row > div:nth-of-type(3)"
#   value_template: "{{ value.split(' ')[1].replace('(B7)\\n\\n\\n', '').replace(',', '.') | float }}"
#   unit_of_measurement: "€/l"
#   scan_interval: 300 #Every 5 minutes 
# - platform: scrape
#   name: referteindexc
#   resource: https://www.spaargids.be/sparen/referte-index-c.html?years=4
#   select: "#main > div.callout-print > div.row.row-nomargin.margin-bottom-1rem > div:nth-of-type(1) > div > h2"
#   value_template: "{{ value.replace('%', '').replace(',', '.') | float }}"
#   unit_of_measurement: "%"
#   scan_interval: 3600 #Every day
- platform: mqtt
  state_topic: "powerswitch/chicken/temperature/0"
  name: "Kippen buiten temperatuur"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "powerswitch/chicken/temperature/1"
  name: "Kippen water temperatuur"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "powerswitch/shed/temperature/0"
  name: "Tuinhuis temperatuur binnen"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "powerswitch/shed/temperature/1"
  name: "Tuinhuis temperatuur buiten"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "powerswitch/livingbol/temperature/0"
  name: "Living temperatuur"
  unit_of_measurement: "°C"
  value_template: "{{ value | round(1) }}"
- platform: mqtt
  state_topic: "powerswitch/livingbol/watt"
  name: "Bol living watt"
  unit_of_measurement: "W"
  value_template: "{{ value | round(0) }}"
- platform: waze_travel_time
  origin: !secret waze_origin_woonwerk
  destination: !secret waze_destination_woonwerk
  region: 'EU'
  name: 'Woon-Werk'
# - platform: haveibeenpwned
#   email: 
#     - !secret email_jeffry
#     - !secret email_katja
# - platform: pi_hole
#   host: !secret pihole_host
#   monitored_conditions:
#     - ads_blocked_today
#     - ads_percentage_today
#     - dns_queries_today
#     - domains_being_blocked
#     - queries_cached
#     - queries_forwarded
#     - unique_clients
#     - unique_domains
# - platform: sonarr
#   api_key: !secret sonarr_api_key
#   host: !secret sonarr_host
#   monitored_conditions:
#     - upcoming
#     - wanted
#   days: 2
# - platform: synologydsm
#   host: !secret synology_host
#   username: !secret synology_username
#   password: !secret synology_password
#   monitored_conditions:
#     - cpu_total_load
#     - memory_real_usage
#     - network_up