- name: Thuis
  latitude: !secret zone_thuis_latitude
  longitude: !secret zone_thuis_longitude
  radius: 250
  icon: mdi:home
- name: PXL
  latitude: !secret zone_pxl_latitude
  longitude: !secret zone_pxl_longitude
  radius: 250
  icon: mdi:worker
- name: Pierre
  latitude: !secret zone_pierre_latitude
  longitude: !secret zone_pierre_longitude
  radius: 250
  icon: mdi:home
- name: Squash
  latitude: !secret zone_squash_latitude
  longitude: !secret zone_squash_longitude
  radius: 250
  icon: mdi:tennis
- name: Kevin
  latitude: !secret zone_kevin_latitude
  longitude: !secret zone_kevin_longitude
  radius: 150
  icon: mdi:account
- name: Kerakris
  latitude: !secret zone_kerakris_latitude
  longitude: !secret zone_kerakris_longitude
  radius: 150
  icon: mdi:store